### ISSUE TITLE
could you make a colab notebook to run auto vicuna?

### ISSUE THREAD

**Issue by GeorvityLabs** [BillSchumacher/Auto-Vicuna#2]
would be great if there was a colab notebook to run vicuna.
we can load weights from huggingface model hub and test it out on colab

**Comment by BillSchumacher** [comment]
Yeah, that seems doable.

**Comment by BillSchumacher** [comment]
Updated README with a colab, I still have to update my code to run the new weight properly though.

**Comment by Peter2023AI** [comment]
Wow, things are moving along fast! 
Image If this was a hybridization between Auto-Vicuna and the Microsoft JARVIS system, where the Auto-Vicuna could run completely on a local system with no API's with local storage, had access to the Internet, and had an option to pull from the HuggingFace repository like Microsoft Jarvis does. Makes me wonder how many people would be able to more easily get involved with different aspects and how quickly it could increase in capabilities as well. All good stuff!👍

**Comment by BillSchumacher** [comment]
There are issues with the colab, I'll fix here in a bit.

**Comment by GeorvityLabs** [comment]
> There are issues with the colab, I'll fix here in a bit.

yes, there are errors.
hope you will test the notebook with the free T4 GPU if possible.

**Comment by GeorvityLabs** [comment]
![Screenshot from 2023-04-13 13-00-15](https://user-images.githubusercontent.com/58555432/231686497-e49abbf1-c1a9-406d-8ecd-b72135c8eeeb.png)
@BillSchumacher

**Comment by BillSchumacher** [comment]
Yeah you can ignore those errors, I successfully was able to apply the delta weights with free.

**Comment by BillSchumacher** [comment]
You can also clone the repo and run the jupyter notebook locally.

**Comment by BillSchumacher** [comment]
I pushed some changes that fix things with the tokenizer name and some notes at the bottom if there are no special tokens in the configs.
