### ISSUE TITLE
Can someone explain how this works in a better Tutrial ?

### ISSUE THREAD

**Issue by emskiemre** [BillSchumacher/Auto-Vicuna#3]
Can't figure it out, need help.

**Comment by BillSchumacher** [comment]
https://colab.research.google.com/github/BillSchumacher/Auto-Vicuna/blob/main/InteractiveManual.ipynb colab here

**Comment by emskiemre** [comment]
# Setup git lfs
!git lfs install --skip-smudge --force
!git lfs env
!git config filter.lfs.process "git-lfs filter-process --skip"
!git config filter.lfs.smudge "git-lfs smudge --skip -- %f"

------------------------------------------------------------------------------------------------------------------------------
Error: Failed to call git rev-parse --git-dir: exit status 128 
Git LFS initialized.
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)
git version 2.25.1

Error: Failed to call git rev-parse --git-dir: exit status 128 
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
GIT_PAGER=cat
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
fatal: not in a git directory
fatal: not in a git directory

**Comment by BillSchumacher** [comment]
Yeah you can ignore that, should still work.

**Comment by BillSchumacher** [comment]
I updated the interactive manual a few days ago, reopen if you still have issues.
