### ISSUE TITLE
The Colab Script need update

### ISSUE THREAD

**Issue by relic-yuexi** [BillSchumacher/Auto-Vicuna#4]
First of all, thank you for your work. However, I encountered some errors when using the colab jupyter script. It might be that you have not updated the script. Could you please update the latest script if it is convenient for you?

**Comment by BillSchumacher** [comment]
If you have specific edits in mind feel free to submit a PR

**Comment by octopushugger** [comment]
I keep encountering this error on the colab:
![image](https://user-images.githubusercontent.com/91927383/232287546-7b6d9e7a-9953-48e0-bc87-ea666773dd85.png)

Which I assume is caused by this code not finishing:
![image](https://user-images.githubusercontent.com/91927383/232287575-f0c21083-8aad-4bb0-aeb3-b461bcf3e82a.png)

Also the colab has the argument written as --vicuna-weights instead of --vicuna_weights.

**Comment by BillSchumacher** [comment]
I updated the colab and am testing it now, thanks for the feedback!

**Comment by BillSchumacher** [comment]
Didn't fix it, I uninstalled tensorflow to clear the error, for some reason colab is doing a ctrl+c on the cell.

**Comment by BillSchumacher** [comment]
It's the system memory I'm pretty sure won't work on the free version.

**Comment by BillSchumacher** [comment]
Yeah, you have to have high mem instance
![image](https://user-images.githubusercontent.com/34168009/232344741-16dd4c4c-af0a-4581-80c0-83af3226ad18.png)

**Comment by BillSchumacher** [comment]
nope, colab pro+ I guess
![image](https://user-images.githubusercontent.com/34168009/232344781-e1d2587d-eaa1-4106-814a-3c9cb02d54f8.png)

![image](https://user-images.githubusercontent.com/34168009/232344792-2129214d-020a-464b-b9fd-190bb73dfb62.png)

**Comment by BillSchumacher** [comment]
Yeah you need a colab+ or maybe connect a local instance
![image](https://user-images.githubusercontent.com/34168009/232345386-7fa7cd19-6c9a-49f1-b1e8-3dae3a77e4a1.png)

**Comment by BillSchumacher** [comment]
I've updated the colab with the requirements.
